#!/bin/sh

# Most of this was taken from "https://github.com/LukeSmithxyz/voidrice/blob/master/.config/aliasrc"

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Run 'acpid' as current user instead of root.
alias \
	acpid="acpid -c $ACPID_CONFIG -s $ACPID_SOCKET -p $ACPID_PID" \
	acpid_restart="pkill acpid ; acpid" \
	acpi_listen="acpi_listen -s $ACPID_SOCKET"

# Custom config files

# Run sqlite3 with config file
alias sqlite3="sqlite3 -init $XDG_CONFIG_HOME/sqlite3/sqliterc"
